import type { ExerciseMetadata } from "./exercise.js";

const SEEDED_AT = "2026-08-07T00:00:00.000Z";

type SeedExercise = Omit<ExerciseMetadata, "createdAt" | "updatedAt" | "revision">;

function seed(input: SeedExercise): ExerciseMetadata {
  return {
    ...input,
    createdAt: SEEDED_AT,
    updatedAt: SEEDED_AT,
    revision: 1,
  };
}

export const CATALOG_SEED: readonly ExerciseMetadata[] = [
  seed({ id: "barbell-back-squat", name: "Barbell Back Squat", kind: "resistance", equipment: ["barbell", "rack"], primaryMuscles: ["quads", "glutes"], secondaryMuscles: ["hamstrings", "core"], movementPattern: "squat", stability: "medium", skillDemand: "high", fatigueClass: "high", supportedRepRanges: [{ min: 4, max: 8 }, { min: 6, max: 10 }], substitutionGroup: "squat-primary" }),
  seed({ id: "leg-press", name: "Leg Press", kind: "resistance", equipment: ["machine"], primaryMuscles: ["quads", "glutes"], secondaryMuscles: ["hamstrings"], movementPattern: "squat", stability: "high", skillDemand: "low", fatigueClass: "medium", supportedRepRanges: [{ min: 8, max: 15 }], substitutionGroup: "squat-primary" }),
  seed({ id: "barbell-rdl", name: "Barbell Romanian Deadlift", kind: "resistance", equipment: ["barbell"], primaryMuscles: ["hamstrings", "glutes"], secondaryMuscles: ["upper_back", "core"], movementPattern: "hinge", stability: "medium", skillDemand: "high", fatigueClass: "high", supportedRepRanges: [{ min: 6, max: 10 }, { min: 8, max: 12 }], substitutionGroup: "hinge-primary" }),
  seed({ id: "dumbbell-rdl", name: "Dumbbell Romanian Deadlift", kind: "resistance", equipment: ["dumbbell"], primaryMuscles: ["hamstrings", "glutes"], secondaryMuscles: ["core"], movementPattern: "hinge", stability: "medium", skillDemand: "medium", fatigueClass: "medium", supportedRepRanges: [{ min: 8, max: 12 }], substitutionGroup: "hinge-primary" }),
  seed({ id: "seated-leg-curl", name: "Seated Leg Curl", kind: "resistance", equipment: ["machine"], primaryMuscles: ["hamstrings"], secondaryMuscles: [], movementPattern: "knee-flexion", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 8, max: 15 }], substitutionGroup: "knee-flexion" }),
  seed({ id: "leg-extension", name: "Leg Extension", kind: "resistance", equipment: ["machine"], primaryMuscles: ["quads"], secondaryMuscles: [], movementPattern: "knee-extension", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 10, max: 15 }], substitutionGroup: "knee-extension" }),
  seed({ id: "barbell-bench-press", name: "Barbell Bench Press", kind: "resistance", equipment: ["barbell", "bench"], primaryMuscles: ["chest"], secondaryMuscles: ["triceps", "side_delts"], movementPattern: "horizontal-push", stability: "medium", skillDemand: "medium", fatigueClass: "medium", supportedRepRanges: [{ min: 4, max: 8 }, { min: 6, max: 10 }], substitutionGroup: "horizontal-push" }),
  seed({ id: "incline-dumbbell-press", name: "Incline Dumbbell Press", kind: "resistance", equipment: ["dumbbell", "bench"], primaryMuscles: ["upper_chest"], secondaryMuscles: ["chest", "triceps", "side_delts"], movementPattern: "horizontal-push", stability: "medium", skillDemand: "medium", fatigueClass: "medium", supportedRepRanges: [{ min: 6, max: 12 }], substitutionGroup: "incline-push" }),
  seed({ id: "machine-chest-press", name: "Machine Chest Press", kind: "resistance", equipment: ["machine"], primaryMuscles: ["chest"], secondaryMuscles: ["triceps"], movementPattern: "horizontal-push", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 8, max: 15 }], substitutionGroup: "horizontal-push" }),
  seed({ id: "barbell-overhead-press", name: "Barbell Overhead Press", kind: "resistance", equipment: ["barbell"], primaryMuscles: ["side_delts"], secondaryMuscles: ["triceps", "upper_chest"], movementPattern: "vertical-push", stability: "medium", skillDemand: "medium", fatigueClass: "medium", supportedRepRanges: [{ min: 5, max: 10 }], substitutionGroup: "vertical-push" }),
  seed({ id: "lat-pulldown", name: "Lat Pulldown", kind: "resistance", equipment: ["cable"], primaryMuscles: ["lats"], secondaryMuscles: ["biceps", "upper_back"], movementPattern: "vertical-pull", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 8, max: 12 }, { min: 10, max: 15 }], substitutionGroup: "vertical-pull" }),
  seed({ id: "assisted-pull-up", name: "Assisted Pull-Up", kind: "resistance", equipment: ["machine"], primaryMuscles: ["lats"], secondaryMuscles: ["biceps", "upper_back"], movementPattern: "vertical-pull", stability: "medium", skillDemand: "medium", fatigueClass: "medium", supportedRepRanges: [{ min: 6, max: 12 }], substitutionGroup: "vertical-pull" }),
  seed({ id: "seated-cable-row", name: "Seated Cable Row", kind: "resistance", equipment: ["cable"], primaryMuscles: ["upper_back"], secondaryMuscles: ["lats", "biceps", "rear_delts"], movementPattern: "horizontal-pull", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 8, max: 15 }], substitutionGroup: "horizontal-pull" }),
  seed({ id: "chest-supported-dumbbell-row", name: "Chest-Supported Dumbbell Row", kind: "resistance", equipment: ["dumbbell", "bench"], primaryMuscles: ["upper_back"], secondaryMuscles: ["lats", "biceps", "rear_delts"], movementPattern: "horizontal-pull", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 8, max: 15 }], substitutionGroup: "horizontal-pull" }),
  seed({ id: "dumbbell-lateral-raise", name: "Dumbbell Lateral Raise", kind: "resistance", equipment: ["dumbbell"], primaryMuscles: ["side_delts"], secondaryMuscles: [], movementPattern: "shoulder-abduction", stability: "medium", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 10, max: 20 }], substitutionGroup: "lateral-raise" }),
  seed({ id: "cable-lateral-raise", name: "Cable Lateral Raise", kind: "resistance", equipment: ["cable"], primaryMuscles: ["side_delts"], secondaryMuscles: [], movementPattern: "shoulder-abduction", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 10, max: 20 }], substitutionGroup: "lateral-raise" }),
  seed({ id: "reverse-pec-deck", name: "Reverse Pec Deck", kind: "resistance", equipment: ["machine"], primaryMuscles: ["rear_delts"], secondaryMuscles: ["upper_back"], movementPattern: "rear-delt", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 10, max: 20 }], substitutionGroup: "rear-delt" }),
  seed({ id: "cable-rear-delt-fly", name: "Cable Rear-Delt Fly", kind: "resistance", equipment: ["cable"], primaryMuscles: ["rear_delts"], secondaryMuscles: ["upper_back"], movementPattern: "rear-delt", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 10, max: 20 }], substitutionGroup: "rear-delt" }),
  seed({ id: "dumbbell-curl", name: "Dumbbell Curl", kind: "resistance", equipment: ["dumbbell"], primaryMuscles: ["biceps"], secondaryMuscles: [], movementPattern: "elbow-flexion", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 8, max: 15 }], substitutionGroup: "biceps-curl" }),
  seed({ id: "cable-triceps-extension", name: "Cable Triceps Extension", kind: "resistance", equipment: ["cable"], primaryMuscles: ["triceps"], secondaryMuscles: [], movementPattern: "elbow-extension", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 8, max: 15 }], substitutionGroup: "triceps-extension" }),
  seed({ id: "standing-calf-raise", name: "Standing Calf Raise", kind: "resistance", equipment: ["machine"], primaryMuscles: ["calves"], secondaryMuscles: [], movementPattern: "plantar-flexion", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 8, max: 20 }], substitutionGroup: "calf-raise" }),
  seed({ id: "plank", name: "Plank", kind: "duration", equipment: [], primaryMuscles: ["core"], secondaryMuscles: [], movementPattern: "anti-extension", stability: "high", skillDemand: "low", fatigueClass: "low", supportedRepRanges: [{ min: 1, max: 1 }], substitutionGroup: "core-bracing" }),
];
