import type { CoachReasonCode } from "./contracts.js";

const explanations: Record<CoachReasonCode, string> = {
  "schedule-prefers-three-days": "Bạn chọn 3 buổi mỗi tuần, nên Full Body giúp mỗi nhóm cơ được tập đều mà vẫn có ngày hồi phục.",
  "schedule-prefers-four-days": "Bạn chọn 4 buổi mỗi tuần, nên Upper/Lower phân bổ thân trên và thân dưới cân bằng trong tuần.",
  "schedule-prefers-six-days": "Bạn chọn 6 buổi mỗi tuần và có đủ khả năng hồi phục, nên Push/Pull/Legs có thể chia nhỏ khối lượng mỗi buổi.",
  "plan-exact-schedule-match": "Số buổi của giáo án khớp trực tiếp với lịch bạn có thể duy trì mỗi tuần.",
  "plan-session-duration-fit": "Thời lượng dự kiến của giáo án phù hợp với giới hạn thời gian bạn đã chọn.",
  "experience-prefers-full-body": "Với mức kinh nghiệm hiện tại, Full Body giúp luyện kỹ thuật thường xuyên mà không dồn quá nhiều bài vào một buổi.",
  "experience-prefers-upper-lower": "Kinh nghiệm hiện tại phù hợp với Upper/Lower để tăng khối lượng nhưng vẫn giữ lịch hồi phục rõ ràng.",
  "experience-prefers-ppl": "Push/Pull/Legs chỉ được ưu tiên khi kinh nghiệm và lịch hồi phục đủ ổn định cho sáu buổi mỗi tuần.",
  "goal-strength-compounds": "Mục tiêu sức mạnh ưu tiên các bài đa khớp chính, khoảng rep thấp hơn và thời gian nghỉ dài hơn.",
  "goal-hypertrophy-volume": "Mục tiêu tăng cơ ưu tiên khối lượng vừa đủ, rep range kiểm soát và tiến bộ từng bước nhỏ.",
  "equipment-safe-substitution": "Bài gốc cần thiết bị bạn chưa chọn, nên LiftPath đã dùng một bài cùng nhóm chuyển động phù hợp với thiết bị hiện có.",
  "restriction-safe-substitution": "Một hạn chế đã được ghi nhận, nên LiftPath đổi sang chuyển động phù hợp hơn thay vì giữ bài gốc.",
  "equipment-prescription-removed": "Không có bài thay thế an toàn với thiết bị hiện có, nên phần này được loại khỏi giáo án thay vì giữ một bài không thể thực hiện.",
  "primary-pattern-unavailable": "Một chuyển động chính không có phương án an toàn tương đương; giáo án được đánh dấu cần kiểm tra trước khi sử dụng.",
  "plan-equipment-safe": "Mọi bài trong phương án này đều dùng được với thiết bị bạn đã chọn.",
  "plan-recommended": "LiftPath chọn phương án có điểm phù hợp cao nhất dựa trên lịch, kinh nghiệm, mục tiêu, thiết bị và thời lượng buổi tập.",
  "session-time-shortened": "Thời gian hôm nay ngắn hơn dự kiến, nên LiftPath bỏ bài phụ trước và giữ các chuyển động chính khi có thể.",
  "readiness-low-energy": "Năng lượng hôm nay thấp, nên buổi tập giữ các bài chính và giảm phần phụ để duy trì kỹ thuật.",
  "readiness-high-soreness": "Mức đau mỏi hôm nay cao, nên LiftPath giảm bớt khối lượng phụ và tránh đẩy effort lên quá cao.",
  "readiness-effort-reduced": "Khả năng hồi phục hôm nay chưa tối ưu, nên mục tiêu effort được giảm một mức để còn thêm rep dự trữ.",
  "pain-blocks-movement": "Bạn báo đau bất thường ở vùng liên quan. LiftPath không tăng tải và đề xuất dừng hoặc đổi chuyển động này.",
  "pain-safe-substitution": "Chuyển động liên quan đến vùng đau đã được thay bằng lựa chọn không dùng mẫu vận động bị ảnh hưởng.",
  "no-adjustment-needed": "Thông tin readiness không cho thấy cần thay đổi; buổi tập được giữ như kế hoạch cơ sở.",
  "insufficient-evidence": "LiftPath chưa có đủ dữ liệu để tự điều chỉnh an toàn; hãy giữ mức hiện tại và đánh giá lại sau buổi tập.",
  "safe-default-plan": "Không thể tạo đầy đủ phương án từ dữ liệu hiện tại, nên LiftPath dùng giáo án Full Body cơ bản và đánh dấu phần cần kiểm tra.",
  "pain-blocks-progression": "Có tín hiệu đau liên quan đến chuyển động này, nên LiftPath không tự tăng tải và yêu cầu bạn đánh giá lại bài tập.",
  "progression-insufficient-history": "Chưa có đủ buổi hoàn chỉnh để đưa ra thay đổi đáng tin cậy; hãy giữ mức hiện tại và thu thập thêm dữ liệu.",
  "progression-top-range-complete": "Tất cả working set đã đạt trần rep với mức gắng sức phù hợp, nên có thể tăng một bước tải nhỏ ở lần tới.",
  "progression-reps-still-building": "Một số working set chưa đạt trần rep, nên giữ tải và tiếp tục tích lũy reps trước khi tăng mức tạ.",
  "progression-linear-success": "Bạn đã hoàn thành mức rep tối thiểu với kỹ thuật và effort phù hợp, nên linear progression có thể tăng một bước tải.",
  "progression-poor-session-observe": "Một buổi chưa đạt mục tiêu chưa đủ để tự giảm tải; LiftPath sẽ giữ mức hiện tại và theo dõi lần tiếp theo.",
  "progression-repeated-below-range": "Hai lần liên tiếp đều dưới khoảng mục tiêu hoặc effort quá cao, nên giảm một bước tải để lấy lại kỹ thuật và rep range.",
  "progression-interruption-guard": "Bạn đã gián đoạn ít nhất 21 ngày, nên lần quay lại không tự tăng tải dù buổi gần nhất từng đạt mục tiêu.",
  "progression-duration-complete": "Toàn bộ working set đã đạt thời lượng mục tiêu, nên lần tới có thể tăng nhẹ số giây.",
  "progression-manual-strategy": "Bài này được đặt ở chế độ điều chỉnh thủ công; LiftPath chỉ hiển thị dữ liệu mà không tự thay đổi mục tiêu.",
  "progression-hold-current": "Dữ liệu hiện tại phù hợp với việc giữ nguyên mục tiêu trong lần tập tiếp theo.",
  "recap-plan-adherence": "Bạn đã hoàn thành phần lớn công việc chính theo kế hoạch của buổi tập.",
  "recap-progression-ready": "Ít nhất một bài đã đủ điều kiện tiến bộ ở lần tập tiếp theo.",
  "recap-personal-record": "Buổi tập có thành tích cá nhân mới được xác định từ dữ liệu đã lưu.",
  "recap-pain-attention": "Ghi nhận đau hoặc khó chịu cần được ưu tiên xem xét trước lần tập tiếp theo.",
  "recap-primary-work-incomplete": "Một phần bài chính chưa hoàn thành, nên lần tới ưu tiên hoàn tất kế hoạch trước khi tăng thêm tải hoặc volume.",
  "recap-recovery-attention": "Phản hồi năng lượng hoặc đau mỏi cho thấy cần thận trọng với khối lượng buổi tiếp theo.",
  "recap-next-session-plan": "LiftPath đã tạo mục tiêu cụ thể cho lần tập tiếp theo từ prescription và dữ liệu của buổi này.",
  "preference-saved": "Lựa chọn bài tập đã được lưu rõ ràng và chỉ được dùng cho các đề xuất sau này khi phù hợp.",
  "preference-cleared": "Lựa chọn bài tập đã được đưa về trung lập và không còn ảnh hưởng đến đề xuất mới.",
};

export const explainReason = (reasonCode: CoachReasonCode) => explanations[reasonCode];

export const COACH_EXPLANATIONS = explanations;
